"""add typing_baselines to customers

Revision ID: 172a26c469ee
Revises: 85a2bec0906d
Create Date: 2026-10-08 11:36:45.897785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # needed for SQLModel-specific column types (e.g. AutoString) that
                 # autogenerate renders into migrations but doesn't import for you


# revision identifiers, used by Alembic.
revision: str = '172a26c469ee'
down_revision: Union[str, Sequence[str], None] = '85a2bec0906d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('typing_baselines', sa.JSON(), server_default=sa.text("'{}'::json"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'typing_baselines')
    # ### end Alembic commands ###
