"""initial schema baseline

Revision ID: 6ee11dab49b6
Revises: 
Create Date: 2026-07-17 23:15:26.400430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ee11dab49b6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('anomaly_model_state', 'flag_threshold',
               existing_type=sa.NUMERIC(precision=6, scale=4),
               comment='Set by ZScoreAnomalyDetector.calibrate_from_scores() against real seed data — not a hardcoded guess. Recalibrate when seed volume changes.',
               existing_comment='Set by calibrate_threshold() against real seed data — not a hardcoded guess. Recalibrate when seed volume changes.',
               existing_nullable=False)
    op.alter_column('transactions', 'geolocation_lat',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment="From /v1/score's geolocation field — NULL when permission was denied or medium is ussd/atm_withdrawal. Persisted here (not just used transiently at score time) so settle's background task can read it back and feed CustomerProfile.location_counts from real traffic.",
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'geolocation_lat',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment="From /v1/score's geolocation field — NULL when permission was denied or medium is ussd/atm_withdrawal. Persisted here (not just used transiently at score time) so settle's background task can read it back and feed CustomerProfile.location_counts from real traffic.",
               existing_nullable=True)
    op.alter_column('anomaly_model_state', 'flag_threshold',
               existing_type=sa.NUMERIC(precision=6, scale=4),
               comment='Set by calibrate_threshold() against real seed data — not a hardcoded guess. Recalibrate when seed volume changes.',
               existing_comment='Set by ZScoreAnomalyDetector.calibrate_from_scores() against real seed data — not a hardcoded guess. Recalibrate when seed volume changes.',
               existing_nullable=False)
    # ### end Alembic commands ###
