"""sync verification columns and drop step_up_method

Revision ID: 85a2bec0906d
Revises: b7dcbfea834d
Create Date: 2026-10-06 20:22:55.763629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # needed for SQLModel-specific column types (e.g. AutoString) that
                 # autogenerate renders into migrations but doesn't import for you


# revision identifiers, used by Alembic.
revision: str = '85a2bec0906d'
down_revision: Union[str, Sequence[str], None] = 'b7dcbfea834d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'destination_key',
               existing_type=sa.VARCHAR(length=100),
               type_=sqlmodel.sql.sqltypes.AutoString(length=128),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'destination_key',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=128),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###
