"""add beneficiary_name to transactions table

Revision ID: 8722262430fd
Revises: 6ee11dab49b6
Create Date: 2026-07-17 23:35:25.410841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8722262430fd'
down_revision: Union[str, Sequence[str], None] = '6ee11dab49b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('beneficiary_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'beneficiary_name')
    # ### end Alembic commands ###
