"""add telemetry column to risk_events

Revision ID: b7dcbfea834d
Revises: 
Create Date: 2026-10-04 18:51:08.215647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # needed for SQLModel-specific column types (e.g. AutoString) that
                 # autogenerate renders into migrations but doesn't import for you


# revision identifiers, used by Alembic.
revision: str = 'b7dcbfea834d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('risk_events', sa.Column('telemetry', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('risk_events', 'telemetry')
    # ### end Alembic commands ###
