"""add beneficiary_name to blacklisted_accounts

Revision ID: eda6a6ccf7fc
Revises: 
Create Date: 2026-07-18 08:59:23.302493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # needed for SQLModel-specific column types (e.g. AutoString) that
                 # autogenerate renders into migrations but doesn't import for you


# revision identifiers, used by Alembic.
revision: str = 'eda6a6ccf7fc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blacklisted_accounts', sa.Column('beneficiary_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blacklisted_accounts', 'beneficiary_name')
    # ### end Alembic commands ###
