from datetime import datetime, timezone
from typing import Any, Optional

from sqlalchemy import BigInteger, Boolean, Column, DateTime, LargeBinary, Numeric
from sqlalchemy import JSON as SAJSON
from sqlmodel import Field, Relationship, SQLModel

Base = SQLModel


def utcnow() -> datetime:
    return datetime.now(timezone.utc)


class Customer(SQLModel, table=True):
    __tablename__ = "customers"

    customer_id: str = Field(default=None, primary_key=True, max_length=64)
    profile_json: dict[str, Any] = Field(
        default_factory=dict,
        sa_column=Column(SAJSON, nullable=False,
                          comment="Mirrors CustomerProfile.to_json(): global_mean/var/n, "
                                  "category_stats per transaction_type, hour_counts, "
                                  "known_beneficiaries, known_bank_codes."),
    )
    transaction_count: int = Field(
        default=0,
        sa_column_kwargs={"comment": "Denormalized from profile_json for Layer 1's cold-start "
                                       "check (is_cold_start = transaction_count < 10) without "
                                       "parsing the full JSON blob on the hot path."},
    )
    created_at: datetime = Field(default_factory=utcnow, sa_column=Column(DateTime(timezone=True), nullable=False))
    updated_at: datetime = Field(default_factory=utcnow, sa_column=Column(DateTime(timezone=True), nullable=False))

    # relationship
    transactions: list["Transaction"] = Relationship(back_populates="customer", sa_relationship_kwargs={"cascade": "all, delete-orphan"})
    risk_events: list["RiskEvent"] = Relationship(back_populates="customer", sa_relationship_kwargs={"cascade": "all, delete-orphan"})


class Transaction(SQLModel, table=True):
    __tablename__ = "transactions"

    id: Optional[int] = Field(default=None, sa_column=Column(BigInteger, primary_key=True, autoincrement=True))
    transaction_reference: str = Field(
        unique=True, max_length=64,
        sa_column_kwargs={"comment": "Generated by the bank app before NIBSS is ever called. "
                                       "Used for idempotency and to correlate with risk_events. "
                                       "NOT the same as nibss_reference below — that one comes "
                                       "from NIBSS itself, only after settlement, and is optional."},
    )
    customer_id: str = Field(foreign_key="customers.customer_id", max_length=64)
    direction: str = Field(
        max_length=10,
        sa_column_kwargs={"comment": "'debit' or 'credit'. Debit feeds the spending baseline, "
                                       "credit feeds income_mean separately — never blended."},
    )
    amount: float = Field(sa_column=Column(Numeric(14, 2), nullable=False))
    beneficiary_account: Optional[str] = Field(default=None, max_length=20)
    beneficiary_bank_code: Optional[str] = Field(
        default=None, max_length=10,
        sa_column_kwargs={"comment": "Real 6-digit NIBSS institution code (e.g. 000013 = "
                                       "GTBank), not the older 3-digit CBN sort code format."},
    )
    transaction_type: str = Field(
        max_length=30,
        sa_column_kwargs={"comment": "Fixed enum validated at the API boundary: transfer, "
                                       "betting, electricity_bill, water_bill, airtime, data, "
                                       "cable_tv. Not inferred by any model."},
    )
    medium: str = Field(
        max_length=20,
        sa_column_kwargs={"comment": "app, ussd, atm_withdrawal, or online_payment. Determines "
                                       "whether 'session' data existed on the originating "
                                       "/v1/score request, and which step_up_method is available."},
    )
    nibss_reference: Optional[str] = Field(
        default=None, max_length=64,
        sa_column_kwargs={"comment": "OPTIONAL, audit-trail only. Not read by any SwiftWolf "
                                       "logic — transaction_reference above is what's load-bearing."},
    )
    final_status: Optional[str] = Field(
        default=None, max_length=20,
        sa_column_kwargs={"comment": "NULL when this row is first created at score time — "
                                       "only set once /v1/transactions/settle fires later."},
    )
    verification_outcome: Optional[str] = Field(
        default=None, max_length=30,
        sa_column_kwargs={"comment": "NULL until settle, same timing as final_status."},
    )
    occurred_at: datetime = Field(
        sa_column=Column(DateTime(timezone=True), nullable=False,
                          comment="The transaction's OWN timestamp, distinct from "
                                  "created_at (row-insert time). All chronological logic "
                                  "(hour bucket, recurring-gap calc) depends on THIS field."),
    )
    created_at: datetime = Field(default_factory=utcnow, sa_column=Column(DateTime(timezone=True), nullable=False))

    customer: Optional[Customer] = Relationship(back_populates="transactions")
    risk_event: Optional["RiskEvent"] = Relationship(back_populates="transaction")


class RiskEvent(SQLModel, table=True):
    __tablename__ = "risk_events"

    id: Optional[int] = Field(default=None, sa_column=Column(BigInteger, primary_key=True, autoincrement=True))
    transaction_reference: str = Field(foreign_key="transactions.transaction_reference", unique=True, max_length=64)
    customer_id: str = Field(foreign_key="customers.customer_id", max_length=64)
    score: int = Field()
    decision: str = Field(max_length=20)
    step_up_method: Optional[str] = Field(default=None, max_length=20)
    reasons: list[str] = Field(default_factory=list, sa_column=Column(SAJSON, nullable=False))
    anomaly_score: Optional[float] = Field(
        default=None,
        sa_column=Column(Numeric(10, 4), nullable=True,
                          comment="HalfSpaceTrees.score_one() output — HIGH = more "
                                  "anomalous (opposite of scikit-learn's convention). "
                                  "This is the model's OUTPUT, not its input."),
    )
    anomaly_flagged: Optional[bool] = Field(default=None, sa_column=Column(Boolean, nullable=True))
    anomaly_zscore: Optional[float] = Field(
        default=None,
        sa_column=Column(Numeric(10, 4), nullable=True,
                          comment="(amount - category_avg) / category_std, computed from "
                                  "the baseline BEFORE this transaction updated it. This "
                                  "is the model's INPUT — different from anomaly_score above."),
    )
    baseline_source: Optional[str] = Field(
        default=None, max_length=20,
        sa_column_kwargs={"comment": "'category' or 'global_fallback' — which baseline "
                                       "get_amount_baseline() actually used for this transaction."},
    )
    created_at: datetime = Field(default_factory=utcnow, sa_column=Column(DateTime(timezone=True), nullable=False))

    customer: Optional[Customer] = Relationship(back_populates="risk_events")
    transaction: Optional[Transaction] = Relationship(back_populates="risk_event")


class AnomalyModelState(SQLModel, table=True):
    __tablename__ = "anomaly_model_state"

    id: Optional[int] = Field(default=None, sa_column=Column(BigInteger, primary_key=True, autoincrement=True))
    model_bytes: bytes = Field(
        sa_column=Column(LargeBinary, nullable=False,
                          comment="Pickled, population-level model — singleton row, NOT "
                                  "per-customer. Pickled (not manually reconstructed like "
                                  "River's stats) since tree structure is too complex to rebuild by hand."),
    )
    flag_threshold: float = Field(
        sa_column=Column(Numeric(6, 4), nullable=False,
                          comment="Set by calibrate_threshold() against real seed data — "
                                  "not a hardcoded guess. Recalibrate when seed volume changes."),
    )
    learned_count: int = Field(default=0)
    skipped_count: int = Field(default=0)
    updated_at: datetime = Field(default_factory=utcnow, sa_column=Column(DateTime(timezone=True), nullable=False))